import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { PostWidget, PostCard, Categories } from "../components";
import { FeaturedPosts } from "../../sections";
// import { FeaturedPosts } from "./../sections";
// import { getPosts } from "../../services/index";
import { getPosts } from "../../services";

// const inter = Inter({ subsets: ["latin"] });

export default function Home({ posts }) {
  return (
    <div className="container mx-auto p-10 mb-8 bg-gray-400">
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedPosts />
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {/* {posts[0].userId} */}
          {posts.map((post) => (
            <PostCard post={post} key={post.title} />
          ))}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const data = await getPosts();
  const posts = await data.json();

  return {
    props: { posts },
  };
}
// http://moviesapi.ir/api/v1/movies?page={page}
